/**
 * generated by Xtext 2.19.0
 */
package no.hal.bdd.bddDsl.impl;

import java.util.Collection;

import no.hal.bdd.bddDsl.ActionDef;
import no.hal.bdd.bddDsl.BddDslPackage;
import no.hal.bdd.bddDsl.EntityDef;
import no.hal.bdd.bddDsl.PropertyDef;
import no.hal.bdd.bddDsl.StateDef;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.EObjectResolvingEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Entity Def</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link no.hal.bdd.bddDsl.impl.EntityDefImpl#getName <em>Name</em>}</li>
 *   <li>{@link no.hal.bdd.bddDsl.impl.EntityDefImpl#getSuperEntities <em>Super Entities</em>}</li>
 *   <li>{@link no.hal.bdd.bddDsl.impl.EntityDefImpl#getActions <em>Actions</em>}</li>
 *   <li>{@link no.hal.bdd.bddDsl.impl.EntityDefImpl#getStates <em>States</em>}</li>
 *   <li>{@link no.hal.bdd.bddDsl.impl.EntityDefImpl#getProperties <em>Properties</em>}</li>
 * </ul>
 *
 * @generated
 */
public class EntityDefImpl extends MinimalEObjectImpl.Container implements EntityDef
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getSuperEntities() <em>Super Entities</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSuperEntities()
   * @generated
   * @ordered
   */
  protected EList<EntityDef> superEntities;

  /**
   * The cached value of the '{@link #getActions() <em>Actions</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getActions()
   * @generated
   * @ordered
   */
  protected EList<ActionDef> actions;

  /**
   * The cached value of the '{@link #getStates() <em>States</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStates()
   * @generated
   * @ordered
   */
  protected EList<StateDef> states;

  /**
   * The cached value of the '{@link #getProperties() <em>Properties</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getProperties()
   * @generated
   * @ordered
   */
  protected EList<PropertyDef> properties;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EntityDefImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return BddDslPackage.Literals.ENTITY_DEF;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, BddDslPackage.ENTITY_DEF__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<EntityDef> getSuperEntities()
  {
    if (superEntities == null)
    {
      superEntities = new EObjectResolvingEList<EntityDef>(EntityDef.class, this, BddDslPackage.ENTITY_DEF__SUPER_ENTITIES);
    }
    return superEntities;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<ActionDef> getActions()
  {
    if (actions == null)
    {
      actions = new EObjectContainmentEList<ActionDef>(ActionDef.class, this, BddDslPackage.ENTITY_DEF__ACTIONS);
    }
    return actions;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<StateDef> getStates()
  {
    if (states == null)
    {
      states = new EObjectContainmentEList<StateDef>(StateDef.class, this, BddDslPackage.ENTITY_DEF__STATES);
    }
    return states;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<PropertyDef> getProperties()
  {
    if (properties == null)
    {
      properties = new EObjectContainmentEList<PropertyDef>(PropertyDef.class, this, BddDslPackage.ENTITY_DEF__PROPERTIES);
    }
    return properties;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case BddDslPackage.ENTITY_DEF__ACTIONS:
        return ((InternalEList<?>)getActions()).basicRemove(otherEnd, msgs);
      case BddDslPackage.ENTITY_DEF__STATES:
        return ((InternalEList<?>)getStates()).basicRemove(otherEnd, msgs);
      case BddDslPackage.ENTITY_DEF__PROPERTIES:
        return ((InternalEList<?>)getProperties()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case BddDslPackage.ENTITY_DEF__NAME:
        return getName();
      case BddDslPackage.ENTITY_DEF__SUPER_ENTITIES:
        return getSuperEntities();
      case BddDslPackage.ENTITY_DEF__ACTIONS:
        return getActions();
      case BddDslPackage.ENTITY_DEF__STATES:
        return getStates();
      case BddDslPackage.ENTITY_DEF__PROPERTIES:
        return getProperties();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case BddDslPackage.ENTITY_DEF__NAME:
        setName((String)newValue);
        return;
      case BddDslPackage.ENTITY_DEF__SUPER_ENTITIES:
        getSuperEntities().clear();
        getSuperEntities().addAll((Collection<? extends EntityDef>)newValue);
        return;
      case BddDslPackage.ENTITY_DEF__ACTIONS:
        getActions().clear();
        getActions().addAll((Collection<? extends ActionDef>)newValue);
        return;
      case BddDslPackage.ENTITY_DEF__STATES:
        getStates().clear();
        getStates().addAll((Collection<? extends StateDef>)newValue);
        return;
      case BddDslPackage.ENTITY_DEF__PROPERTIES:
        getProperties().clear();
        getProperties().addAll((Collection<? extends PropertyDef>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case BddDslPackage.ENTITY_DEF__NAME:
        setName(NAME_EDEFAULT);
        return;
      case BddDslPackage.ENTITY_DEF__SUPER_ENTITIES:
        getSuperEntities().clear();
        return;
      case BddDslPackage.ENTITY_DEF__ACTIONS:
        getActions().clear();
        return;
      case BddDslPackage.ENTITY_DEF__STATES:
        getStates().clear();
        return;
      case BddDslPackage.ENTITY_DEF__PROPERTIES:
        getProperties().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case BddDslPackage.ENTITY_DEF__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case BddDslPackage.ENTITY_DEF__SUPER_ENTITIES:
        return superEntities != null && !superEntities.isEmpty();
      case BddDslPackage.ENTITY_DEF__ACTIONS:
        return actions != null && !actions.isEmpty();
      case BddDslPackage.ENTITY_DEF__STATES:
        return states != null && !states.isEmpty();
      case BddDslPackage.ENTITY_DEF__PROPERTIES:
        return properties != null && !properties.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //EntityDefImpl
