/*
 * generated by Xtext 2.18.0.M3
 */
package no.hal.bdd.ide

import com.google.inject.Guice
import no.hal.bdd.BddDslRuntimeModule
import no.hal.bdd.BddDslStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class BddDslIdeSetup extends BddDslStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new BddDslRuntimeModule, new BddDslIdeModule))
	}
	
}
