/**
 * generated by Xtext 2.19.0
 */
package no.hal.bdd.bddDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Action Phrase</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see no.hal.bdd.bddDsl.BddDslPackage#getActionPhrase()
 * @model
 * @generated
 */
public interface ActionPhrase extends EObject
{
} // ActionPhrase
