/**
 * generated by Xtext 2.19.0
 */
package no.hal.bdd.bddDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Entity Def</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link no.hal.bdd.bddDsl.EntityDef#getName <em>Name</em>}</li>
 *   <li>{@link no.hal.bdd.bddDsl.EntityDef#getSuperEntities <em>Super Entities</em>}</li>
 *   <li>{@link no.hal.bdd.bddDsl.EntityDef#getActions <em>Actions</em>}</li>
 *   <li>{@link no.hal.bdd.bddDsl.EntityDef#getStates <em>States</em>}</li>
 *   <li>{@link no.hal.bdd.bddDsl.EntityDef#getProperties <em>Properties</em>}</li>
 * </ul>
 *
 * @see no.hal.bdd.bddDsl.BddDslPackage#getEntityDef()
 * @model
 * @generated
 */
public interface EntityDef extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see no.hal.bdd.bddDsl.BddDslPackage#getEntityDef_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link no.hal.bdd.bddDsl.EntityDef#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Super Entities</b></em>' reference list.
   * The list contents are of type {@link no.hal.bdd.bddDsl.EntityDef}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Super Entities</em>' reference list.
   * @see no.hal.bdd.bddDsl.BddDslPackage#getEntityDef_SuperEntities()
   * @model
   * @generated
   */
  EList<EntityDef> getSuperEntities();

  /**
   * Returns the value of the '<em><b>Actions</b></em>' containment reference list.
   * The list contents are of type {@link no.hal.bdd.bddDsl.ActionDef}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Actions</em>' containment reference list.
   * @see no.hal.bdd.bddDsl.BddDslPackage#getEntityDef_Actions()
   * @model containment="true"
   * @generated
   */
  EList<ActionDef> getActions();

  /**
   * Returns the value of the '<em><b>States</b></em>' containment reference list.
   * The list contents are of type {@link no.hal.bdd.bddDsl.StateDef}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>States</em>' containment reference list.
   * @see no.hal.bdd.bddDsl.BddDslPackage#getEntityDef_States()
   * @model containment="true"
   * @generated
   */
  EList<StateDef> getStates();

  /**
   * Returns the value of the '<em><b>Properties</b></em>' containment reference list.
   * The list contents are of type {@link no.hal.bdd.bddDsl.PropertyDef}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Properties</em>' containment reference list.
   * @see no.hal.bdd.bddDsl.BddDslPackage#getEntityDef_Properties()
   * @model containment="true"
   * @generated
   */
  EList<PropertyDef> getProperties();

} // EntityDef
