/**
 * generated by Xtext 2.19.0
 */
package no.hal.bdd.bddDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link no.hal.bdd.bddDsl.Model#getName <em>Name</em>}</li>
 *   <li>{@link no.hal.bdd.bddDsl.Model#getModelRefs <em>Model Refs</em>}</li>
 *   <li>{@link no.hal.bdd.bddDsl.Model#getEntityDefs <em>Entity Defs</em>}</li>
 *   <li>{@link no.hal.bdd.bddDsl.Model#getScenarios <em>Scenarios</em>}</li>
 * </ul>
 *
 * @see no.hal.bdd.bddDsl.BddDslPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see no.hal.bdd.bddDsl.BddDslPackage#getModel_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link no.hal.bdd.bddDsl.Model#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Model Refs</b></em>' containment reference list.
   * The list contents are of type {@link no.hal.bdd.bddDsl.ModelRef}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Model Refs</em>' containment reference list.
   * @see no.hal.bdd.bddDsl.BddDslPackage#getModel_ModelRefs()
   * @model containment="true"
   * @generated
   */
  EList<ModelRef> getModelRefs();

  /**
   * Returns the value of the '<em><b>Entity Defs</b></em>' containment reference list.
   * The list contents are of type {@link no.hal.bdd.bddDsl.EntityDef}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entity Defs</em>' containment reference list.
   * @see no.hal.bdd.bddDsl.BddDslPackage#getModel_EntityDefs()
   * @model containment="true"
   * @generated
   */
  EList<EntityDef> getEntityDefs();

  /**
   * Returns the value of the '<em><b>Scenarios</b></em>' containment reference list.
   * The list contents are of type {@link no.hal.bdd.bddDsl.Scenario}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Scenarios</em>' containment reference list.
   * @see no.hal.bdd.bddDsl.BddDslPackage#getModel_Scenarios()
   * @model containment="true"
   * @generated
   */
  EList<Scenario> getScenarios();

} // Model
