/**
 * generated by Xtext 2.19.0
 */
package no.hal.bdd.bddDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Scenario Ref</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link no.hal.bdd.bddDsl.ScenarioRef#getScenarioRef <em>Scenario Ref</em>}</li>
 * </ul>
 *
 * @see no.hal.bdd.bddDsl.BddDslPackage#getScenarioRef()
 * @model
 * @generated
 */
public interface ScenarioRef extends StatePhrase
{
  /**
   * Returns the value of the '<em><b>Scenario Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Scenario Ref</em>' reference.
   * @see #setScenarioRef(Scenario)
   * @see no.hal.bdd.bddDsl.BddDslPackage#getScenarioRef_ScenarioRef()
   * @model
   * @generated
   */
  Scenario getScenarioRef();

  /**
   * Sets the value of the '{@link no.hal.bdd.bddDsl.ScenarioRef#getScenarioRef <em>Scenario Ref</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Scenario Ref</em>' reference.
   * @see #getScenarioRef()
   * @generated
   */
  void setScenarioRef(Scenario value);

} // ScenarioRef
