/**
 * generated by Xtext 2.25.0
 */
package no.hal.bdd.bddDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Scenario</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link no.hal.bdd.bddDsl.Scenario#getName <em>Name</em>}</li>
 *   <li>{@link no.hal.bdd.bddDsl.Scenario#getPreStateE <em>Pre State E</em>}</li>
 *   <li>{@link no.hal.bdd.bddDsl.Scenario#getPreState <em>Pre State</em>}</li>
 *   <li>{@link no.hal.bdd.bddDsl.Scenario#getAction <em>Action</em>}</li>
 *   <li>{@link no.hal.bdd.bddDsl.Scenario#getPostState <em>Post State</em>}</li>
 *   <li>{@link no.hal.bdd.bddDsl.Scenario#getActionE <em>Action E</em>}</li>
 *   <li>{@link no.hal.bdd.bddDsl.Scenario#getPreState1 <em>Pre State1</em>}</li>
 *   <li>{@link no.hal.bdd.bddDsl.Scenario#getAction1 <em>Action1</em>}</li>
 *   <li>{@link no.hal.bdd.bddDsl.Scenario#getPostState1 <em>Post State1</em>}</li>
 *   <li>{@link no.hal.bdd.bddDsl.Scenario#getPreStateE1 <em>Pre State E1</em>}</li>
 *   <li>{@link no.hal.bdd.bddDsl.Scenario#getPreState2 <em>Pre State2</em>}</li>
 *   <li>{@link no.hal.bdd.bddDsl.Scenario#getAction2 <em>Action2</em>}</li>
 *   <li>{@link no.hal.bdd.bddDsl.Scenario#getPostState2 <em>Post State2</em>}</li>
 * </ul>
 *
 * @see no.hal.bdd.bddDsl.BddDslPackage#getScenario()
 * @model
 * @generated
 */
public interface Scenario extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see no.hal.bdd.bddDsl.BddDslPackage#getScenario_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link no.hal.bdd.bddDsl.Scenario#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Pre State E</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pre State E</em>' containment reference.
   * @see #setPreStateE(ScenarioState)
   * @see no.hal.bdd.bddDsl.BddDslPackage#getScenario_PreStateE()
   * @model containment="true"
   * @generated
   */
  ScenarioState getPreStateE();

  /**
   * Sets the value of the '{@link no.hal.bdd.bddDsl.Scenario#getPreStateE <em>Pre State E</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pre State E</em>' containment reference.
   * @see #getPreStateE()
   * @generated
   */
  void setPreStateE(ScenarioState value);

  /**
   * Returns the value of the '<em><b>Pre State</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pre State</em>' containment reference.
   * @see #setPreState(ScenarioState)
   * @see no.hal.bdd.bddDsl.BddDslPackage#getScenario_PreState()
   * @model containment="true"
   * @generated
   */
  ScenarioState getPreState();

  /**
   * Sets the value of the '{@link no.hal.bdd.bddDsl.Scenario#getPreState <em>Pre State</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pre State</em>' containment reference.
   * @see #getPreState()
   * @generated
   */
  void setPreState(ScenarioState value);

  /**
   * Returns the value of the '<em><b>Action</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Action</em>' containment reference.
   * @see #setAction(ScenarioAction)
   * @see no.hal.bdd.bddDsl.BddDslPackage#getScenario_Action()
   * @model containment="true"
   * @generated
   */
  ScenarioAction getAction();

  /**
   * Sets the value of the '{@link no.hal.bdd.bddDsl.Scenario#getAction <em>Action</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Action</em>' containment reference.
   * @see #getAction()
   * @generated
   */
  void setAction(ScenarioAction value);

  /**
   * Returns the value of the '<em><b>Post State</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Post State</em>' containment reference.
   * @see #setPostState(ScenarioState)
   * @see no.hal.bdd.bddDsl.BddDslPackage#getScenario_PostState()
   * @model containment="true"
   * @generated
   */
  ScenarioState getPostState();

  /**
   * Sets the value of the '{@link no.hal.bdd.bddDsl.Scenario#getPostState <em>Post State</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Post State</em>' containment reference.
   * @see #getPostState()
   * @generated
   */
  void setPostState(ScenarioState value);

  /**
   * Returns the value of the '<em><b>Action E</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Action E</em>' containment reference.
   * @see #setActionE(ScenarioAction)
   * @see no.hal.bdd.bddDsl.BddDslPackage#getScenario_ActionE()
   * @model containment="true"
   * @generated
   */
  ScenarioAction getActionE();

  /**
   * Sets the value of the '{@link no.hal.bdd.bddDsl.Scenario#getActionE <em>Action E</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Action E</em>' containment reference.
   * @see #getActionE()
   * @generated
   */
  void setActionE(ScenarioAction value);

  /**
   * Returns the value of the '<em><b>Pre State1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pre State1</em>' containment reference.
   * @see #setPreState1(ScenarioState)
   * @see no.hal.bdd.bddDsl.BddDslPackage#getScenario_PreState1()
   * @model containment="true"
   * @generated
   */
  ScenarioState getPreState1();

  /**
   * Sets the value of the '{@link no.hal.bdd.bddDsl.Scenario#getPreState1 <em>Pre State1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pre State1</em>' containment reference.
   * @see #getPreState1()
   * @generated
   */
  void setPreState1(ScenarioState value);

  /**
   * Returns the value of the '<em><b>Action1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Action1</em>' containment reference.
   * @see #setAction1(ScenarioAction)
   * @see no.hal.bdd.bddDsl.BddDslPackage#getScenario_Action1()
   * @model containment="true"
   * @generated
   */
  ScenarioAction getAction1();

  /**
   * Sets the value of the '{@link no.hal.bdd.bddDsl.Scenario#getAction1 <em>Action1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Action1</em>' containment reference.
   * @see #getAction1()
   * @generated
   */
  void setAction1(ScenarioAction value);

  /**
   * Returns the value of the '<em><b>Post State1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Post State1</em>' containment reference.
   * @see #setPostState1(ScenarioState)
   * @see no.hal.bdd.bddDsl.BddDslPackage#getScenario_PostState1()
   * @model containment="true"
   * @generated
   */
  ScenarioState getPostState1();

  /**
   * Sets the value of the '{@link no.hal.bdd.bddDsl.Scenario#getPostState1 <em>Post State1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Post State1</em>' containment reference.
   * @see #getPostState1()
   * @generated
   */
  void setPostState1(ScenarioState value);

  /**
   * Returns the value of the '<em><b>Pre State E1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pre State E1</em>' containment reference.
   * @see #setPreStateE1(ScenarioState)
   * @see no.hal.bdd.bddDsl.BddDslPackage#getScenario_PreStateE1()
   * @model containment="true"
   * @generated
   */
  ScenarioState getPreStateE1();

  /**
   * Sets the value of the '{@link no.hal.bdd.bddDsl.Scenario#getPreStateE1 <em>Pre State E1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pre State E1</em>' containment reference.
   * @see #getPreStateE1()
   * @generated
   */
  void setPreStateE1(ScenarioState value);

  /**
   * Returns the value of the '<em><b>Pre State2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pre State2</em>' containment reference.
   * @see #setPreState2(ScenarioState)
   * @see no.hal.bdd.bddDsl.BddDslPackage#getScenario_PreState2()
   * @model containment="true"
   * @generated
   */
  ScenarioState getPreState2();

  /**
   * Sets the value of the '{@link no.hal.bdd.bddDsl.Scenario#getPreState2 <em>Pre State2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pre State2</em>' containment reference.
   * @see #getPreState2()
   * @generated
   */
  void setPreState2(ScenarioState value);

  /**
   * Returns the value of the '<em><b>Action2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Action2</em>' containment reference.
   * @see #setAction2(ScenarioAction)
   * @see no.hal.bdd.bddDsl.BddDslPackage#getScenario_Action2()
   * @model containment="true"
   * @generated
   */
  ScenarioAction getAction2();

  /**
   * Sets the value of the '{@link no.hal.bdd.bddDsl.Scenario#getAction2 <em>Action2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Action2</em>' containment reference.
   * @see #getAction2()
   * @generated
   */
  void setAction2(ScenarioAction value);

  /**
   * Returns the value of the '<em><b>Post State2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Post State2</em>' containment reference.
   * @see #setPostState2(ScenarioState)
   * @see no.hal.bdd.bddDsl.BddDslPackage#getScenario_PostState2()
   * @model containment="true"
   * @generated
   */
  ScenarioState getPostState2();

  /**
   * Sets the value of the '{@link no.hal.bdd.bddDsl.Scenario#getPostState2 <em>Post State2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Post State2</em>' containment reference.
   * @see #getPostState2()
   * @generated
   */
  void setPostState2(ScenarioState value);

} // Scenario
