/**
 * generated by Xtext 2.19.0
 */
package no.hal.bdd.bddDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Simple Value</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see no.hal.bdd.bddDsl.BddDslPackage#getSimpleValue()
 * @model
 * @generated
 */
public interface SimpleValue extends PropertyValue
{
} // SimpleValue
