/**
 * generated by Xtext 2.19.0
 */
package no.hal.bdd.bddDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Verb Action</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link no.hal.bdd.bddDsl.VerbAction#getAction <em>Action</em>}</li>
 *   <li>{@link no.hal.bdd.bddDsl.VerbAction#getEntity <em>Entity</em>}</li>
 * </ul>
 *
 * @see no.hal.bdd.bddDsl.BddDslPackage#getVerbAction()
 * @model
 * @generated
 */
public interface VerbAction extends ActionPhrase
{
  /**
   * Returns the value of the '<em><b>Action</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Action</em>' containment reference.
   * @see #setAction(ActionRef)
   * @see no.hal.bdd.bddDsl.BddDslPackage#getVerbAction_Action()
   * @model containment="true"
   * @generated
   */
  ActionRef getAction();

  /**
   * Sets the value of the '{@link no.hal.bdd.bddDsl.VerbAction#getAction <em>Action</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Action</em>' containment reference.
   * @see #getAction()
   * @generated
   */
  void setAction(ActionRef value);

  /**
   * Returns the value of the '<em><b>Entity</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entity</em>' containment reference.
   * @see #setEntity(EntityRef)
   * @see no.hal.bdd.bddDsl.BddDslPackage#getVerbAction_Entity()
   * @model containment="true"
   * @generated
   */
  EntityRef getEntity();

  /**
   * Sets the value of the '{@link no.hal.bdd.bddDsl.VerbAction#getEntity <em>Entity</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Entity</em>' containment reference.
   * @see #getEntity()
   * @generated
   */
  void setEntity(EntityRef value);

} // VerbAction
