/**
 * generated by Xtext 2.18.0.M3
 */
package no.hal.bdd.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import no.hal.bdd.BddDslRuntimeModule;
import no.hal.bdd.BddDslStandaloneSetup;
import no.hal.bdd.ide.BddDslIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class BddDslIdeSetup extends BddDslStandaloneSetup {
  @Override
  public Injector createInjector() {
    BddDslRuntimeModule _bddDslRuntimeModule = new BddDslRuntimeModule();
    BddDslIdeModule _bddDslIdeModule = new BddDslIdeModule();
    return Guice.createInjector(Modules2.mixin(_bddDslRuntimeModule, _bddDslIdeModule));
  }
}
