/**
 * generated by Xtext 2.18.0.M3
 */
package no.hal.bdd.ide;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class BddDslIdeModule extends AbstractBddDslIdeModule {
}
