/*
 * generated by Xtext 2.18.0.M3
 */
package no.hal.bdd


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class BddDslRuntimeModule extends AbstractBddDslRuntimeModule {
}
