/**
 * generated by Xtext 2.18.0.M3
 */
package no.hal.bdd;

import no.hal.bdd.BddDslStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class BddDslStandaloneSetup extends BddDslStandaloneSetupGenerated {
  public static void doSetup() {
    new BddDslStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
