/*
 * generated by Xtext 2.25.0
 */
package no.hal.bdd.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import no.hal.bdd.ide.contentassist.antlr.internal.InternalBddDslParser;
import no.hal.bdd.services.BddDslGrammarAccess;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class BddDslParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(BddDslGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, BddDslGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getModelAccess().getAlternatives_1(), "rule__Model__Alternatives_1");
			builder.put(grammarAccess.getEntityDefAccess().getNameAlternatives_1_0(), "rule__EntityDef__NameAlternatives_1_0");
			builder.put(grammarAccess.getEntityDefAccess().getAlternatives_5_4_0(), "rule__EntityDef__Alternatives_5_4_0");
			builder.put(grammarAccess.getEntityDefAccess().getAlternatives_6_4_0(), "rule__EntityDef__Alternatives_6_4_0");
			builder.put(grammarAccess.getEntityDefAccess().getAlternatives_7_4_0(), "rule__EntityDef__Alternatives_7_4_0");
			builder.put(grammarAccess.getActionDefAccess().getAlternatives_1(), "rule__ActionDef__Alternatives_1");
			builder.put(grammarAccess.getActionDefAccess().getAlternatives_4(), "rule__ActionDef__Alternatives_4");
			builder.put(grammarAccess.getActionDefAccess().getAlternatives_4_1_1(), "rule__ActionDef__Alternatives_4_1_1");
			builder.put(grammarAccess.getPREPAccess().getAlternatives(), "rule__PREP__Alternatives");
			builder.put(grammarAccess.getStateNameAccess().getAlternatives_1(), "rule__StateName__Alternatives_1");
			builder.put(grammarAccess.getID_OR_STRINGAccess().getAlternatives(), "rule__ID_OR_STRING__Alternatives");
			builder.put(grammarAccess.getScenarioAccess().getAlternatives_3(), "rule__Scenario__Alternatives_3");
			builder.put(grammarAccess.getScenarioAccess().getAlternatives_5(), "rule__Scenario__Alternatives_5");
			builder.put(grammarAccess.getScenarioAccess().getAlternatives_7(), "rule__Scenario__Alternatives_7");
			builder.put(grammarAccess.getScenarioAccess().getAlternatives_9(), "rule__Scenario__Alternatives_9");
			builder.put(grammarAccess.getScenarioAccess().getAlternatives_11_0_0(), "rule__Scenario__Alternatives_11_0_0");
			builder.put(grammarAccess.getScenarioAccess().getAlternatives_11_0_0_0_0(), "rule__Scenario__Alternatives_11_0_0_0_0");
			builder.put(grammarAccess.getScenarioAccess().getAlternatives_11_0_0_1_1(), "rule__Scenario__Alternatives_11_0_0_1_1");
			builder.put(grammarAccess.getScenarioAccess().getAlternatives_11_1_1(), "rule__Scenario__Alternatives_11_1_1");
			builder.put(grammarAccess.getScenarioAccess().getAlternatives_11_1_3(), "rule__Scenario__Alternatives_11_1_3");
			builder.put(grammarAccess.getScenarioAccess().getAlternatives_11_1_4(), "rule__Scenario__Alternatives_11_1_4");
			builder.put(grammarAccess.getScenarioAccess().getAlternatives_11_1_4_1_1(), "rule__Scenario__Alternatives_11_1_4_1_1");
			builder.put(grammarAccess.getScenarioAccess().getAlternatives_11_1_6(), "rule__Scenario__Alternatives_11_1_6");
			builder.put(grammarAccess.getScenarioAccess().getAlternatives_11_1_9(), "rule__Scenario__Alternatives_11_1_9");
			builder.put(grammarAccess.getScenarioAccess().getAlternatives_11_1_12(), "rule__Scenario__Alternatives_11_1_12");
			builder.put(grammarAccess.getScenarioAccess().getAlternatives_11_1_13(), "rule__Scenario__Alternatives_11_1_13");
			builder.put(grammarAccess.getScenarioAccess().getAlternatives_11_1_13_1_1(), "rule__Scenario__Alternatives_11_1_13_1_1");
			builder.put(grammarAccess.getScenarioAccess().getAlternatives_11_2_0(), "rule__Scenario__Alternatives_11_2_0");
			builder.put(grammarAccess.getScenarioAccess().getAlternatives_11_2_0_0_0(), "rule__Scenario__Alternatives_11_2_0_0_0");
			builder.put(grammarAccess.getScenarioAccess().getAlternatives_11_2_0_1_0(), "rule__Scenario__Alternatives_11_2_0_1_0");
			builder.put(grammarAccess.getScenarioAccess().getAlternatives_11_3_1(), "rule__Scenario__Alternatives_11_3_1");
			builder.put(grammarAccess.getScenarioAccess().getAlternatives_11_3_3(), "rule__Scenario__Alternatives_11_3_3");
			builder.put(grammarAccess.getScenarioAccess().getAlternatives_11_3_4(), "rule__Scenario__Alternatives_11_3_4");
			builder.put(grammarAccess.getScenarioAccess().getAlternatives_11_3_4_1_1(), "rule__Scenario__Alternatives_11_3_4_1_1");
			builder.put(grammarAccess.getScenarioAccess().getAlternatives_11_3_6(), "rule__Scenario__Alternatives_11_3_6");
			builder.put(grammarAccess.getScenarioAccess().getAlternatives_11_5(), "rule__Scenario__Alternatives_11_5");
			builder.put(grammarAccess.getScenarioAccess().getAlternatives_11_8(), "rule__Scenario__Alternatives_11_8");
			builder.put(grammarAccess.getScenarioAccess().getAlternatives_11_9(), "rule__Scenario__Alternatives_11_9");
			builder.put(grammarAccess.getScenarioAccess().getAlternatives_11_9_1_1(), "rule__Scenario__Alternatives_11_9_1_1");
			builder.put(grammarAccess.getScenarioAccess().getAlternatives_12_0_0(), "rule__Scenario__Alternatives_12_0_0");
			builder.put(grammarAccess.getScenarioAccess().getAlternatives_12_0_0_0_0(), "rule__Scenario__Alternatives_12_0_0_0_0");
			builder.put(grammarAccess.getScenarioAccess().getAlternatives_12_0_0_1_1(), "rule__Scenario__Alternatives_12_0_0_1_1");
			builder.put(grammarAccess.getScenarioAccess().getAlternatives_12_1_1(), "rule__Scenario__Alternatives_12_1_1");
			builder.put(grammarAccess.getScenarioAccess().getAlternatives_12_1_3(), "rule__Scenario__Alternatives_12_1_3");
			builder.put(grammarAccess.getScenarioAccess().getAlternatives_12_1_4(), "rule__Scenario__Alternatives_12_1_4");
			builder.put(grammarAccess.getScenarioAccess().getAlternatives_12_1_4_1_1(), "rule__Scenario__Alternatives_12_1_4_1_1");
			builder.put(grammarAccess.getScenarioAccess().getAlternatives_12_1_6(), "rule__Scenario__Alternatives_12_1_6");
			builder.put(grammarAccess.getScenarioAccess().getAlternatives_12_3(), "rule__Scenario__Alternatives_12_3");
			builder.put(grammarAccess.getScenarioAccess().getAlternatives_12_6(), "rule__Scenario__Alternatives_12_6");
			builder.put(grammarAccess.getScenarioAccess().getAlternatives_12_7(), "rule__Scenario__Alternatives_12_7");
			builder.put(grammarAccess.getScenarioAccess().getAlternatives_12_7_1_1(), "rule__Scenario__Alternatives_12_7_1_1");
			builder.put(grammarAccess.getScenarioStateAccess().getAlternatives_1_0(), "rule__ScenarioState__Alternatives_1_0");
			builder.put(grammarAccess.getScenarioActionAccess().getAlternatives_1_0(), "rule__ScenarioAction__Alternatives_1_0");
			builder.put(grammarAccess.getStatePhraseAccess().getAlternatives(), "rule__StatePhrase__Alternatives");
			builder.put(grammarAccess.getENTITY_IDENTITYAccess().getAlternatives_1(), "rule__ENTITY_IDENTITY__Alternatives_1");
			builder.put(grammarAccess.getOPTIONAccess().getAlternatives_1(), "rule__OPTION__Alternatives_1");
			builder.put(grammarAccess.getEntityRefAccess().getAlternatives(), "rule__EntityRef__Alternatives");
			builder.put(grammarAccess.getEntityRefAccess().getAlternatives_0_1(), "rule__EntityRef__Alternatives_0_1");
			builder.put(grammarAccess.getEntityRefAccess().getAlternatives_0_2_0(), "rule__EntityRef__Alternatives_0_2_0");
			builder.put(grammarAccess.getEntityStatePhraseAccess().getAlternatives_0_1(), "rule__EntityStatePhrase__Alternatives_0_1");
			builder.put(grammarAccess.getEntityStatePhraseAccess().getAlternatives_0_3(), "rule__EntityStatePhrase__Alternatives_0_3");
			builder.put(grammarAccess.getEntityStatePhraseAccess().getAlternatives_0_4(), "rule__EntityStatePhrase__Alternatives_0_4");
			builder.put(grammarAccess.getEntityStatePhraseAccess().getAlternatives_2(), "rule__EntityStatePhrase__Alternatives_2");
			builder.put(grammarAccess.getEntityPropertyStatePhraseAccess().getAlternatives_1(), "rule__EntityPropertyStatePhrase__Alternatives_1");
			builder.put(grammarAccess.getEntityPropertyStatePhraseAccess().getAlternatives_3(), "rule__EntityPropertyStatePhrase__Alternatives_3");
			builder.put(grammarAccess.getEntityPropertyStatePhraseAccess().getAlternatives_5(), "rule__EntityPropertyStatePhrase__Alternatives_5");
			builder.put(grammarAccess.getEntityPropertyStatePhraseAccess().getAlternatives_5_0_0_0(), "rule__EntityPropertyStatePhrase__Alternatives_5_0_0_0");
			builder.put(grammarAccess.getEntityPropertyStatePhraseAccess().getAlternatives_5_1_0(), "rule__EntityPropertyStatePhrase__Alternatives_5_1_0");
			builder.put(grammarAccess.getEntityPropertyStatePhraseAccess().getAlternatives_5_1_0_0_0(), "rule__EntityPropertyStatePhrase__Alternatives_5_1_0_0_0");
			builder.put(grammarAccess.getPropertyValueAccess().getAlternatives(), "rule__PropertyValue__Alternatives");
			builder.put(grammarAccess.getSimpleValueAccess().getAlternatives(), "rule__SimpleValue__Alternatives");
			builder.put(grammarAccess.getTRUEAccess().getAlternatives(), "rule__TRUE__Alternatives");
			builder.put(grammarAccess.getFALSEAccess().getAlternatives(), "rule__FALSE__Alternatives");
			builder.put(grammarAccess.getBooleanValueAccess().getValueAlternatives_0(), "rule__BooleanValue__ValueAlternatives_0");
			builder.put(grammarAccess.getActionPhraseAccess().getAlternatives(), "rule__ActionPhrase__Alternatives");
			builder.put(grammarAccess.getVerbActionAccess().getAlternatives_5(), "rule__VerbAction__Alternatives_5");
			builder.put(grammarAccess.getVerbActionAccess().getAlternatives_7(), "rule__VerbAction__Alternatives_7");
			builder.put(grammarAccess.getVerbActionAccess().getAlternatives_9(), "rule__VerbAction__Alternatives_9");
			builder.put(grammarAccess.getVerbActionAccess().getAlternatives_10(), "rule__VerbAction__Alternatives_10");
			builder.put(grammarAccess.getActionRefAccess().getAlternatives_4_0(), "rule__ActionRef__Alternatives_4_0");
			builder.put(grammarAccess.getModelAccess().getGroup(), "rule__Model__Group__0");
			builder.put(grammarAccess.getModelAccess().getGroup_0(), "rule__Model__Group_0__0");
			builder.put(grammarAccess.getModelRefAccess().getGroup(), "rule__ModelRef__Group__0");
			builder.put(grammarAccess.getEntityDefAccess().getGroup(), "rule__EntityDef__Group__0");
			builder.put(grammarAccess.getEntityDefAccess().getGroup_2(), "rule__EntityDef__Group_2__0");
			builder.put(grammarAccess.getEntityDefAccess().getGroup_3(), "rule__EntityDef__Group_3__0");
			builder.put(grammarAccess.getEntityDefAccess().getGroup_3_2(), "rule__EntityDef__Group_3_2__0");
			builder.put(grammarAccess.getEntityDefAccess().getGroup_5(), "rule__EntityDef__Group_5__0");
			builder.put(grammarAccess.getEntityDefAccess().getGroup_5_3(), "rule__EntityDef__Group_5_3__0");
			builder.put(grammarAccess.getEntityDefAccess().getGroup_5_4(), "rule__EntityDef__Group_5_4__0");
			builder.put(grammarAccess.getEntityDefAccess().getGroup_6(), "rule__EntityDef__Group_6__0");
			builder.put(grammarAccess.getEntityDefAccess().getGroup_6_3(), "rule__EntityDef__Group_6_3__0");
			builder.put(grammarAccess.getEntityDefAccess().getGroup_6_4(), "rule__EntityDef__Group_6_4__0");
			builder.put(grammarAccess.getEntityDefAccess().getGroup_7(), "rule__EntityDef__Group_7__0");
			builder.put(grammarAccess.getEntityDefAccess().getGroup_7_3(), "rule__EntityDef__Group_7_3__0");
			builder.put(grammarAccess.getEntityDefAccess().getGroup_7_4(), "rule__EntityDef__Group_7_4__0");
			builder.put(grammarAccess.getActionDefAccess().getGroup(), "rule__ActionDef__Group__0");
			builder.put(grammarAccess.getActionDefAccess().getGroup_4_1(), "rule__ActionDef__Group_4_1__0");
			builder.put(grammarAccess.getActionDefAccess().getGroup_4_1_1_3(), "rule__ActionDef__Group_4_1_1_3__0");
			builder.put(grammarAccess.getStateDefAccess().getGroup(), "rule__StateDef__Group__0");
			builder.put(grammarAccess.getStateDefAccess().getGroup_2(), "rule__StateDef__Group_2__0");
			builder.put(grammarAccess.getStateNameAccess().getGroup(), "rule__StateName__Group__0");
			builder.put(grammarAccess.getPropertyDefAccess().getGroup(), "rule__PropertyDef__Group__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup(), "rule__Scenario__Group__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_3_6(), "rule__Scenario__Group_3_6__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_11(), "rule__Scenario__Group_11__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_11_0(), "rule__Scenario__Group_11_0__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_11_0_0_0(), "rule__Scenario__Group_11_0_0_0__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_11_0_0_0_0_0(), "rule__Scenario__Group_11_0_0_0_0_0__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_11_0_0_0_0_1(), "rule__Scenario__Group_11_0_0_0_0_1__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_11_0_0_0_1(), "rule__Scenario__Group_11_0_0_0_1__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_11_0_0_1(), "rule__Scenario__Group_11_0_0_1__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_11_0_0_1_1_1(), "rule__Scenario__Group_11_0_0_1_1_1__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_11_0_0_1_2(), "rule__Scenario__Group_11_0_0_1_2__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_11_1(), "rule__Scenario__Group_11_1__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_11_1_1_1(), "rule__Scenario__Group_11_1_1_1__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_11_1_3_4(), "rule__Scenario__Group_11_1_3_4__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_11_1_4_1(), "rule__Scenario__Group_11_1_4_1__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_11_1_4_2(), "rule__Scenario__Group_11_1_4_2__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_11_1_6_0(), "rule__Scenario__Group_11_1_6_0__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_11_1_6_1(), "rule__Scenario__Group_11_1_6_1__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_11_1_6_2(), "rule__Scenario__Group_11_1_6_2__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_11_1_6_3(), "rule__Scenario__Group_11_1_6_3__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_11_1_9_1(), "rule__Scenario__Group_11_1_9_1__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_11_1_12_4(), "rule__Scenario__Group_11_1_12_4__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_11_1_13_1(), "rule__Scenario__Group_11_1_13_1__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_11_1_13_2(), "rule__Scenario__Group_11_1_13_2__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_11_2(), "rule__Scenario__Group_11_2__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_11_2_0_0(), "rule__Scenario__Group_11_2_0_0__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_11_2_0_0_0_0(), "rule__Scenario__Group_11_2_0_0_0_0__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_11_2_0_0_0_1(), "rule__Scenario__Group_11_2_0_0_0_1__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_11_2_0_0_0_3(), "rule__Scenario__Group_11_2_0_0_0_3__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_11_2_0_0_1(), "rule__Scenario__Group_11_2_0_0_1__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_11_2_0_1(), "rule__Scenario__Group_11_2_0_1__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_11_2_0_1_0_0(), "rule__Scenario__Group_11_2_0_1_0_0__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_11_2_0_1_0_1(), "rule__Scenario__Group_11_2_0_1_0_1__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_11_2_0_1_0_2(), "rule__Scenario__Group_11_2_0_1_0_2__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_11_2_0_1_0_3(), "rule__Scenario__Group_11_2_0_1_0_3__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_11_3(), "rule__Scenario__Group_11_3__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_11_3_1_1(), "rule__Scenario__Group_11_3_1_1__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_11_3_3_4(), "rule__Scenario__Group_11_3_3_4__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_11_3_4_1(), "rule__Scenario__Group_11_3_4_1__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_11_3_4_2(), "rule__Scenario__Group_11_3_4_2__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_11_3_6_0(), "rule__Scenario__Group_11_3_6_0__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_11_3_6_1(), "rule__Scenario__Group_11_3_6_1__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_11_3_6_2(), "rule__Scenario__Group_11_3_6_2__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_11_3_6_3(), "rule__Scenario__Group_11_3_6_3__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_11_5_1(), "rule__Scenario__Group_11_5_1__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_11_8_4(), "rule__Scenario__Group_11_8_4__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_11_9_1(), "rule__Scenario__Group_11_9_1__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_11_9_2(), "rule__Scenario__Group_11_9_2__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_12(), "rule__Scenario__Group_12__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_12_0(), "rule__Scenario__Group_12_0__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_12_0_0_0(), "rule__Scenario__Group_12_0_0_0__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_12_0_0_0_0_0(), "rule__Scenario__Group_12_0_0_0_0_0__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_12_0_0_0_0_1(), "rule__Scenario__Group_12_0_0_0_0_1__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_12_0_0_0_1(), "rule__Scenario__Group_12_0_0_0_1__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_12_0_0_1(), "rule__Scenario__Group_12_0_0_1__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_12_0_0_1_1_1(), "rule__Scenario__Group_12_0_0_1_1_1__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_12_0_0_1_2(), "rule__Scenario__Group_12_0_0_1_2__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_12_1(), "rule__Scenario__Group_12_1__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_12_1_1_1(), "rule__Scenario__Group_12_1_1_1__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_12_1_3_4(), "rule__Scenario__Group_12_1_3_4__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_12_1_4_1(), "rule__Scenario__Group_12_1_4_1__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_12_1_4_2(), "rule__Scenario__Group_12_1_4_2__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_12_1_6_0(), "rule__Scenario__Group_12_1_6_0__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_12_1_6_1(), "rule__Scenario__Group_12_1_6_1__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_12_1_6_2(), "rule__Scenario__Group_12_1_6_2__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_12_1_6_3(), "rule__Scenario__Group_12_1_6_3__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_12_3_1(), "rule__Scenario__Group_12_3_1__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_12_6_4(), "rule__Scenario__Group_12_6_4__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_12_7_1(), "rule__Scenario__Group_12_7_1__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_12_7_2(), "rule__Scenario__Group_12_7_2__0");
			builder.put(grammarAccess.getScenarioStateAccess().getGroup(), "rule__ScenarioState__Group__0");
			builder.put(grammarAccess.getScenarioStateAccess().getGroup_1(), "rule__ScenarioState__Group_1__0");
			builder.put(grammarAccess.getScenarioStateAccess().getGroup_1_0_1(), "rule__ScenarioState__Group_1_0_1__0");
			builder.put(grammarAccess.getScenarioActionAccess().getGroup(), "rule__ScenarioAction__Group__0");
			builder.put(grammarAccess.getScenarioActionAccess().getGroup_1(), "rule__ScenarioAction__Group_1__0");
			builder.put(grammarAccess.getScenarioActionAccess().getGroup_1_0_0(), "rule__ScenarioAction__Group_1_0_0__0");
			builder.put(grammarAccess.getENTITY_IDENTITYAccess().getGroup(), "rule__ENTITY_IDENTITY__Group__0");
			builder.put(grammarAccess.getOPTIONAccess().getGroup(), "rule__OPTION__Group__0");
			builder.put(grammarAccess.getEntityRefAccess().getGroup_0(), "rule__EntityRef__Group_0__0");
			builder.put(grammarAccess.getEntityRefAccess().getGroup_0_0(), "rule__EntityRef__Group_0_0__0");
			builder.put(grammarAccess.getEntityRefAccess().getGroup_0_2(), "rule__EntityRef__Group_0_2__0");
			builder.put(grammarAccess.getEntityRefAccess().getGroup_0_2_0_1(), "rule__EntityRef__Group_0_2_0_1__0");
			builder.put(grammarAccess.getEntityStatePhraseAccess().getGroup(), "rule__EntityStatePhrase__Group__0");
			builder.put(grammarAccess.getEntityStatePhraseAccess().getGroup_0(), "rule__EntityStatePhrase__Group_0__0");
			builder.put(grammarAccess.getEntityStatePhraseAccess().getGroup_0_1_1(), "rule__EntityStatePhrase__Group_0_1_1__0");
			builder.put(grammarAccess.getEntityStatePhraseAccess().getGroup_0_3_1(), "rule__EntityStatePhrase__Group_0_3_1__0");
			builder.put(grammarAccess.getEntityStatePhraseAccess().getGroup_0_4_1(), "rule__EntityStatePhrase__Group_0_4_1__0");
			builder.put(grammarAccess.getEntityStatePhraseAccess().getGroup_0_4_2(), "rule__EntityStatePhrase__Group_0_4_2__0");
			builder.put(grammarAccess.getEntityPropertyStatePhraseAccess().getGroup(), "rule__EntityPropertyStatePhrase__Group__0");
			builder.put(grammarAccess.getEntityPropertyStatePhraseAccess().getGroup_1_1(), "rule__EntityPropertyStatePhrase__Group_1_1__0");
			builder.put(grammarAccess.getEntityPropertyStatePhraseAccess().getGroup_3_3(), "rule__EntityPropertyStatePhrase__Group_3_3__0");
			builder.put(grammarAccess.getEntityPropertyStatePhraseAccess().getGroup_3_4(), "rule__EntityPropertyStatePhrase__Group_3_4__0");
			builder.put(grammarAccess.getEntityPropertyStatePhraseAccess().getGroup_5_0(), "rule__EntityPropertyStatePhrase__Group_5_0__0");
			builder.put(grammarAccess.getEntityPropertyStatePhraseAccess().getGroup_5_0_0(), "rule__EntityPropertyStatePhrase__Group_5_0_0__0");
			builder.put(grammarAccess.getEntityPropertyStatePhraseAccess().getGroup_5_0_0_0_1(), "rule__EntityPropertyStatePhrase__Group_5_0_0_0_1__0");
			builder.put(grammarAccess.getEntityPropertyStatePhraseAccess().getGroup_5_1(), "rule__EntityPropertyStatePhrase__Group_5_1__0");
			builder.put(grammarAccess.getEntityPropertyStatePhraseAccess().getGroup_5_1_0_0(), "rule__EntityPropertyStatePhrase__Group_5_1_0_0__0");
			builder.put(grammarAccess.getEntityPropertyStatePhraseAccess().getGroup_5_1_0_0_0_1(), "rule__EntityPropertyStatePhrase__Group_5_1_0_0_0_1__0");
			builder.put(grammarAccess.getEntityPropertyStatePhraseAccess().getGroup_5_1_0_1(), "rule__EntityPropertyStatePhrase__Group_5_1_0_1__0");
			builder.put(grammarAccess.getListValueAccess().getGroup(), "rule__ListValue__Group__0");
			builder.put(grammarAccess.getListValueAccess().getGroup_2(), "rule__ListValue__Group_2__0");
			builder.put(grammarAccess.getListValueAccess().getGroup_2_1(), "rule__ListValue__Group_2_1__0");
			builder.put(grammarAccess.getSetValueAccess().getGroup(), "rule__SetValue__Group__0");
			builder.put(grammarAccess.getSetValueAccess().getGroup_2(), "rule__SetValue__Group_2__0");
			builder.put(grammarAccess.getSetValueAccess().getGroup_2_1(), "rule__SetValue__Group_2_1__0");
			builder.put(grammarAccess.getVerbActionAccess().getGroup(), "rule__VerbAction__Group__0");
			builder.put(grammarAccess.getVerbActionAccess().getGroup_4(), "rule__VerbAction__Group_4__0");
			builder.put(grammarAccess.getVerbActionAccess().getGroup_5_0(), "rule__VerbAction__Group_5_0__0");
			builder.put(grammarAccess.getVerbActionAccess().getGroup_10_2(), "rule__VerbAction__Group_10_2__0");
			builder.put(grammarAccess.getVerbActionAccess().getGroup_10_3(), "rule__VerbAction__Group_10_3__0");
			builder.put(grammarAccess.getActionRefAccess().getGroup(), "rule__ActionRef__Group__0");
			builder.put(grammarAccess.getActionRefAccess().getGroup_4(), "rule__ActionRef__Group_4__0");
			builder.put(grammarAccess.getVerifyActionAccess().getGroup(), "rule__VerifyAction__Group__0");
			builder.put(grammarAccess.getModelAccess().getNameAssignment_0_1(), "rule__Model__NameAssignment_0_1");
			builder.put(grammarAccess.getModelAccess().getModelRefsAssignment_1_0(), "rule__Model__ModelRefsAssignment_1_0");
			builder.put(grammarAccess.getModelAccess().getEntityDefsAssignment_1_1(), "rule__Model__EntityDefsAssignment_1_1");
			builder.put(grammarAccess.getModelAccess().getScenariosAssignment_1_2(), "rule__Model__ScenariosAssignment_1_2");
			builder.put(grammarAccess.getModelRefAccess().getModelRefAssignment_1(), "rule__ModelRef__ModelRefAssignment_1");
			builder.put(grammarAccess.getEntityDefAccess().getNameAssignment_1(), "rule__EntityDef__NameAssignment_1");
			builder.put(grammarAccess.getEntityDefAccess().getSuperEntitiesAssignment_3_1(), "rule__EntityDef__SuperEntitiesAssignment_3_1");
			builder.put(grammarAccess.getEntityDefAccess().getSuperEntitiesAssignment_3_2_1(), "rule__EntityDef__SuperEntitiesAssignment_3_2_1");
			builder.put(grammarAccess.getEntityDefAccess().getActionsAssignment_5_1(), "rule__EntityDef__ActionsAssignment_5_1");
			builder.put(grammarAccess.getEntityDefAccess().getActionsAssignment_5_4_1(), "rule__EntityDef__ActionsAssignment_5_4_1");
			builder.put(grammarAccess.getEntityDefAccess().getStatesAssignment_6_1(), "rule__EntityDef__StatesAssignment_6_1");
			builder.put(grammarAccess.getEntityDefAccess().getStatesAssignment_6_4_1(), "rule__EntityDef__StatesAssignment_6_4_1");
			builder.put(grammarAccess.getEntityDefAccess().getPropertiesAssignment_7_1(), "rule__EntityDef__PropertiesAssignment_7_1");
			builder.put(grammarAccess.getEntityDefAccess().getPropertiesAssignment_7_4_1(), "rule__EntityDef__PropertiesAssignment_7_4_1");
			builder.put(grammarAccess.getActionDefAccess().getNameAssignment_0(), "rule__ActionDef__NameAssignment_0");
			builder.put(grammarAccess.getActionDefAccess().getArgumentAssignment_3(), "rule__ActionDef__ArgumentAssignment_3");
			builder.put(grammarAccess.getActionDefAccess().getPrepositionAssignment_4_0(), "rule__ActionDef__PrepositionAssignment_4_0");
			builder.put(grammarAccess.getActionDefAccess().getOptionalPrefAssignment_4_1_0(), "rule__ActionDef__OptionalPrefAssignment_4_1_0");
			builder.put(grammarAccess.getActionDefAccess().getPrepositionAssignment_4_1_1_0(), "rule__ActionDef__PrepositionAssignment_4_1_1_0");
			builder.put(grammarAccess.getStateDefAccess().getPostiveAssignment_0(), "rule__StateDef__PostiveAssignment_0");
			builder.put(grammarAccess.getStateDefAccess().getNegativeAssignment_2_1(), "rule__StateDef__NegativeAssignment_2_1");
			builder.put(grammarAccess.getStateNameAccess().getNameAssignment_0(), "rule__StateName__NameAssignment_0");
			builder.put(grammarAccess.getPropertyDefAccess().getNameAssignment_0(), "rule__PropertyDef__NameAssignment_0");
			builder.put(grammarAccess.getPropertyDefAccess().getPluralAssignment_1(), "rule__PropertyDef__PluralAssignment_1");
			builder.put(grammarAccess.getScenarioAccess().getNameAssignment_1(), "rule__Scenario__NameAssignment_1");
			builder.put(grammarAccess.getScenarioAccess().getPreStateEAssignment_11_0_0_1_3(), "rule__Scenario__PreStateEAssignment_11_0_0_1_3");
			builder.put(grammarAccess.getScenarioAccess().getPreStateAssignment_11_1_2(), "rule__Scenario__PreStateAssignment_11_1_2");
			builder.put(grammarAccess.getScenarioAccess().getActionAssignment_11_1_7(), "rule__Scenario__ActionAssignment_11_1_7");
			builder.put(grammarAccess.getScenarioAccess().getPostStateAssignment_11_1_11(), "rule__Scenario__PostStateAssignment_11_1_11");
			builder.put(grammarAccess.getScenarioAccess().getActionEAssignment_11_2_0_1_1(), "rule__Scenario__ActionEAssignment_11_2_0_1_1");
			builder.put(grammarAccess.getScenarioAccess().getPreState1Assignment_11_3_2(), "rule__Scenario__PreState1Assignment_11_3_2");
			builder.put(grammarAccess.getScenarioAccess().getAction1Assignment_11_3_7(), "rule__Scenario__Action1Assignment_11_3_7");
			builder.put(grammarAccess.getScenarioAccess().getPostState1Assignment_11_7(), "rule__Scenario__PostState1Assignment_11_7");
			builder.put(grammarAccess.getScenarioAccess().getPreStateE1Assignment_12_0_0_1_3(), "rule__Scenario__PreStateE1Assignment_12_0_0_1_3");
			builder.put(grammarAccess.getScenarioAccess().getPreState2Assignment_12_1_2(), "rule__Scenario__PreState2Assignment_12_1_2");
			builder.put(grammarAccess.getScenarioAccess().getAction2Assignment_12_1_7(), "rule__Scenario__Action2Assignment_12_1_7");
			builder.put(grammarAccess.getScenarioAccess().getPostState2Assignment_12_5(), "rule__Scenario__PostState2Assignment_12_5");
			builder.put(grammarAccess.getScenarioStateAccess().getStatesAssignment_0(), "rule__ScenarioState__StatesAssignment_0");
			builder.put(grammarAccess.getScenarioStateAccess().getStatesAssignment_1_1(), "rule__ScenarioState__StatesAssignment_1_1");
			builder.put(grammarAccess.getScenarioActionAccess().getActionsAssignment_0(), "rule__ScenarioAction__ActionsAssignment_0");
			builder.put(grammarAccess.getScenarioActionAccess().getActionsAssignment_1_1(), "rule__ScenarioAction__ActionsAssignment_1_1");
			builder.put(grammarAccess.getScenarioRefAccess().getScenarioRefAssignment(), "rule__ScenarioRef__ScenarioRefAssignment");
			builder.put(grammarAccess.getEntityRefAccess().getEntityAssignment_0_2_1(), "rule__EntityRef__EntityAssignment_0_2_1");
			builder.put(grammarAccess.getEntityRefAccess().getNameAssignment_0_2_2(), "rule__EntityRef__NameAssignment_0_2_2");
			builder.put(grammarAccess.getEntityRefAccess().getNameAssignment_1(), "rule__EntityRef__NameAssignment_1");
			builder.put(grammarAccess.getEntityStatePhraseAccess().getPropertyAssignment_0_0(), "rule__EntityStatePhrase__PropertyAssignment_0_0");
			builder.put(grammarAccess.getEntityStatePhraseAccess().getEntityAssignment_1(), "rule__EntityStatePhrase__EntityAssignment_1");
			builder.put(grammarAccess.getEntityStatePhraseAccess().getStateAssignment_4(), "rule__EntityStatePhrase__StateAssignment_4");
			builder.put(grammarAccess.getEntityPropertyStatePhraseAccess().getPropertyAssignment_0(), "rule__EntityPropertyStatePhrase__PropertyAssignment_0");
			builder.put(grammarAccess.getEntityPropertyStatePhraseAccess().getEntityAssignment_4(), "rule__EntityPropertyStatePhrase__EntityAssignment_4");
			builder.put(grammarAccess.getEntityPropertyStatePhraseAccess().getValueAssignment_5_0_0_1(), "rule__EntityPropertyStatePhrase__ValueAssignment_5_0_0_1");
			builder.put(grammarAccess.getEntityPropertyStatePhraseAccess().getValuesAssignment_5_1_0_0_1(), "rule__EntityPropertyStatePhrase__ValuesAssignment_5_1_0_0_1");
			builder.put(grammarAccess.getEntityPropertyStatePhraseAccess().getValuesAssignment_5_1_0_1_1(), "rule__EntityPropertyStatePhrase__ValuesAssignment_5_1_0_1_1");
			builder.put(grammarAccess.getListValueAccess().getValuesAssignment_2_0(), "rule__ListValue__ValuesAssignment_2_0");
			builder.put(grammarAccess.getListValueAccess().getValuesAssignment_2_1_1(), "rule__ListValue__ValuesAssignment_2_1_1");
			builder.put(grammarAccess.getSetValueAccess().getValuesAssignment_2_0(), "rule__SetValue__ValuesAssignment_2_0");
			builder.put(grammarAccess.getSetValueAccess().getValuesAssignment_2_1_1(), "rule__SetValue__ValuesAssignment_2_1_1");
			builder.put(grammarAccess.getStringValueAccess().getValueAssignment(), "rule__StringValue__ValueAssignment");
			builder.put(grammarAccess.getIntValueAccess().getValueAssignment(), "rule__IntValue__ValueAssignment");
			builder.put(grammarAccess.getBooleanValueAccess().getValueAssignment(), "rule__BooleanValue__ValueAssignment");
			builder.put(grammarAccess.getVerbActionAccess().getActionAssignment_0(), "rule__VerbAction__ActionAssignment_0");
			builder.put(grammarAccess.getVerbActionAccess().getEntityAssignment_6(), "rule__VerbAction__EntityAssignment_6");
			builder.put(grammarAccess.getVerbActionAccess().getEntityAssignment_8(), "rule__VerbAction__EntityAssignment_8");
			builder.put(grammarAccess.getVerbActionAccess().getEntityAssignment_12(), "rule__VerbAction__EntityAssignment_12");
			builder.put(grammarAccess.getActionRefAccess().getVerbAssignment_0(), "rule__ActionRef__VerbAssignment_0");
			builder.put(grammarAccess.getActionRefAccess().getArgumentAssignment_2(), "rule__ActionRef__ArgumentAssignment_2");
			builder.put(grammarAccess.getActionRefAccess().getPrepositionAssignment_3(), "rule__ActionRef__PrepositionAssignment_3");
			builder.put(grammarAccess.getActionRefAccess().getEntityAssignment_4_1(), "rule__ActionRef__EntityAssignment_4_1");
			builder.put(grammarAccess.getVerifyActionAccess().getStateAssignment_1(), "rule__VerifyAction__StateAssignment_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private BddDslGrammarAccess grammarAccess;

	@Override
	protected InternalBddDslParser createParser() {
		InternalBddDslParser result = new InternalBddDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public BddDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(BddDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
