/*
 * generated by Xtext 2.18.0.M3
 */
package no.hal.bdd.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractBddDslScopeProvider extends DelegatingScopeProvider {
}
