/*
 * generated by Xtext 2.25.0
 */
package no.hal.bdd.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractBddDslScopeProvider extends DelegatingScopeProvider {
}
